name: Run Python Script Daily at 27:30 JST

on:
  schedule:
    - cron: '30 18 * * *'  # 毎日UTCの18:30（日本時間のJSTでは27:30）に実行
  workflow_dispatch:  # 手動での実行を可能にする


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
         pip install requests beautifulsoup4 googlemaps pandas tqdm gspread oauth2client gspread_dataframe  pytz

    - name: Run script
      env:
        GOOGLEAPIKEY: ${{ secrets.GOOGLEAPIKEY }}
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
      run: python main.py
